[2024-12-06 18:06:05,236] torch.distributed.run: [WARNING] 
[2024-12-06 18:06:05,236] torch.distributed.run: [WARNING] *****************************************
[2024-12-06 18:06:05,236] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
[2024-12-06 18:06:05,236] torch.distributed.run: [WARNING] *****************************************
/home/ma-user/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/site-packages/torch_npu/contrib/transfer_to_npu.py:260: RuntimeWarning: torch.jit.script and torch.jit.script_method will be disabled by transfer_to_npu, which currently does not support them, if you need to enable them, please do not use transfer_to_npu.
  warnings.warn(msg, RuntimeWarning)
/home/ma-user/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/site-packages/torch_npu/contrib/transfer_to_npu.py:299: ImportWarning: 
    *************************************************************************************************************
    The torch.Tensor.cuda and torch.nn.Module.cuda are replaced with torch.Tensor.npu and torch.nn.Module.npu now..
    The torch.cuda.DoubleTensor is replaced with torch.npu.FloatTensor cause the double type is not supported now..
    The backend in torch.distributed.init_process_group set to hccl now..
    The torch.cuda.* and torch.cuda.amp.* are replaced with torch.npu.* and torch.npu.amp.* now..
    The device parameters have been replaced with npu in the function below:
    torch.logspace, torch.randint, torch.hann_window, torch.rand, torch.full_like, torch.ones_like, torch.rand_like, torch.randperm, torch.arange, torch.frombuffer, torch.normal, torch._empty_per_channel_affine_quantized, torch.empty_strided, torch.empty_like, torch.scalar_tensor, torch.tril_indices, torch.bartlett_window, torch.ones, torch.sparse_coo_tensor, torch.randn, torch.kaiser_window, torch.tensor, torch.triu_indices, torch.as_tensor, torch.zeros, torch.randint_like, torch.full, torch.eye, torch._sparse_csr_tensor_unsafe, torch.empty, torch._sparse_coo_tensor_unsafe, torch.blackman_window, torch.zeros_like, torch.range, torch.sparse_csr_tensor, torch.randn_like, torch.from_file, torch._cudnn_init_dropout_state, torch._empty_affine_quantized, torch.linspace, torch.hamming_window, torch.empty_quantized, torch._pin_memory, torch.autocast, torch.load, torch.Generator, torch.Tensor.new_empty, torch.Tensor.new_empty_strided, torch.Tensor.new_full, torch.Tensor.new_ones, torch.Tensor.new_tensor, torch.Tensor.new_zeros, torch.Tensor.to, torch.nn.Module.to, torch.nn.Module.to_empty
    *************************************************************************************************************
    
  warnings.warn(msg, ImportWarning)
/home/ma-user/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/site-packages/torch_npu/contrib/transfer_to_npu.py:260: RuntimeWarning: torch.jit.script and torch.jit.script_method will be disabled by transfer_to_npu, which currently does not support them, if you need to enable them, please do not use transfer_to_npu.
  warnings.warn(msg, RuntimeWarning)
/home/ma-user/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/site-packages/torch_npu/contrib/transfer_to_npu.py:260: RuntimeWarning: torch.jit.script and torch.jit.script_method will be disabled by transfer_to_npu, which currently does not support them, if you need to enable them, please do not use transfer_to_npu.
  warnings.warn(msg, RuntimeWarning)
/home/ma-user/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/site-packages/torch_npu/contrib/transfer_to_npu.py:260: RuntimeWarning: torch.jit.script and torch.jit.script_method will be disabled by transfer_to_npu, which currently does not support them, if you need to enable them, please do not use transfer_to_npu.
  warnings.warn(msg, RuntimeWarning)
/home/ma-user/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/site-packages/torch_npu/contrib/transfer_to_npu.py:260: RuntimeWarning: torch.jit.script and torch.jit.script_method will be disabled by transfer_to_npu, which currently does not support them, if you need to enable them, please do not use transfer_to_npu.
  warnings.warn(msg, RuntimeWarning)
/home/ma-user/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/site-packages/torch_npu/contrib/transfer_to_npu.py:260: RuntimeWarning: torch.jit.script and torch.jit.script_method will be disabled by transfer_to_npu, which currently does not support them, if you need to enable them, please do not use transfer_to_npu.
  warnings.warn(msg, RuntimeWarning)
/home/ma-user/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/site-packages/torch_npu/contrib/transfer_to_npu.py:260: RuntimeWarning: torch.jit.script and torch.jit.script_method will be disabled by transfer_to_npu, which currently does not support them, if you need to enable them, please do not use transfer_to_npu.
  warnings.warn(msg, RuntimeWarning)
/home/ma-user/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/site-packages/torch_npu/contrib/transfer_to_npu.py:260: RuntimeWarning: torch.jit.script and torch.jit.script_method will be disabled by transfer_to_npu, which currently does not support them, if you need to enable them, please do not use transfer_to_npu.
  warnings.warn(msg, RuntimeWarning)
Using /root/.cache/torch_extensions/py39_cpu as PyTorch extensions root...
Emitting ninja build file /root/.cache/torch_extensions/py39_cpu/adaptive_cp/build.ninja...
Building extension module adaptive_cp...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
Using /root/.cache/torch_extensions/py39_cpu as PyTorch extensions root...
Using /root/.cache/torch_extensions/py39_cpu as PyTorch extensions root...
Using /root/.cache/torch_extensions/py39_cpu as PyTorch extensions root...
ninja: no work to do.
Loading extension module adaptive_cp...
Loading extension module adaptive_cp...
Using /root/.cache/torch_extensions/py39_cpu as PyTorch extensions root...
Using /root/.cache/torch_extensions/py39_cpu as PyTorch extensions root...
Using /root/.cache/torch_extensions/py39_cpu as PyTorch extensions root...
Using /root/.cache/torch_extensions/py39_cpu as PyTorch extensions root...
Emitting ninja build file /root/.cache/torch_extensions/py39_cpu/adaptive_cp/build.ninja...
Building extension module adaptive_cp...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module adaptive_cp...
Loading extension module adaptive_cp...
Loading extension module adaptive_cp...
Loading extension module adaptive_cp...
Loading extension module adaptive_cp...
Loading extension module adaptive_cp...
##############################
!!!!!!!!!!!!!!!!!!!
##############################
!!!!!!!!!!!!!!!!!!!
Traceback (most recent call last):
  File "/workspace/RC4/ModelLink/pretrain_gpt.py", line 229, in <module>
    main()
  File "/workspace/RC4/ModelLink/pretrain_gpt.py", line 222, in main
    pretrain(train_valid_test_datasets_provider,
  File "/workspace/RC4/ModelLink/modellink/training/training.py", line 291, in pretrain
    initialize_megatron(extra_args_provider=extra_args_provider,
  File "/workspace/RC4/ModelLink/modellink/training/initialize.py", line 72, in initialize_megatron
    args = parse_args(extra_args_provider, ignore_unknown_args)
  File "/workspace/RC4/ModelLink/modellink/training/arguments.py", line 37, in wrapper
    return parse_args(decorated_provider, ignore_unknown_args)
  File "/workspace/RC4/ModelLink/modellink/training/arguments.py", line 37, in wrapper
    return parse_args(decorated_provider, ignore_unknown_args)
  File "/workspace/RC4/ModelLink/megatron/training/arguments.py", line 86, in parse_args
    args = load_json_args(args.flexpipe_config, args)
  File "/workspace/RC4/ModelLink/megatron/training/json_arguments.py", line 13, in load_json_args
    args.flex_recompute_activations = config_dict["flex_recompute_activations"]
KeyError: 'flex_recompute_activations'
[ERROR] 2024-12-06-18:06:13 (PID:225415, Device:-1, RankID:-1) ERR99999 UNKNOWN application exception
/home/ma-user/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/tempfile.py:821: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmpqe46z2yy'>
  _warnings.warn(warn_message, ResourceWarning)
Traceback (most recent call last):
  File "/workspace/RC4/ModelLink/pretrain_gpt.py", line 229, in <module>
    main()
  File "/workspace/RC4/ModelLink/pretrain_gpt.py", line 222, in main
    pretrain(train_valid_test_datasets_provider,
  File "/workspace/RC4/ModelLink/modellink/training/training.py", line 291, in pretrain
    initialize_megatron(extra_args_provider=extra_args_provider,
  File "/workspace/RC4/ModelLink/modellink/training/initialize.py", line 72, in initialize_megatron
    args = parse_args(extra_args_provider, ignore_unknown_args)
  File "/workspace/RC4/ModelLink/modellink/training/arguments.py", line 37, in wrapper
    return parse_args(decorated_provider, ignore_unknown_args)
  File "/workspace/RC4/ModelLink/modellink/training/arguments.py", line 37, in wrapper
    return parse_args(decorated_provider, ignore_unknown_args)
  File "/workspace/RC4/ModelLink/megatron/training/arguments.py", line 86, in parse_args
    args = load_json_args(args.flexpipe_config, args)
  File "/workspace/RC4/ModelLink/megatron/training/json_arguments.py", line 13, in load_json_args
    args.flex_recompute_activations = config_dict["flex_recompute_activations"]
KeyError: 'flex_recompute_activations'
[ERROR] 2024-12-06-18:06:13 (PID:225408, Device:-1, RankID:-1) ERR99999 UNKNOWN application exception
/home/ma-user/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/tempfile.py:821: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmp8cd6mj6c'>
  _warnings.warn(warn_message, ResourceWarning)
##############################
!!!!!!!!!!!!!!!!!!!
##############################
!!!!!!!!!!!!!!!!!!!
Traceback (most recent call last):
  File "/workspace/RC4/ModelLink/pretrain_gpt.py", line 229, in <module>
    main()
  File "/workspace/RC4/ModelLink/pretrain_gpt.py", line 222, in main
Traceback (most recent call last):
  File "/workspace/RC4/ModelLink/pretrain_gpt.py", line 229, in <module>
    pretrain(train_valid_test_datasets_provider,
  File "/workspace/RC4/ModelLink/modellink/training/training.py", line 291, in pretrain
    main()
  File "/workspace/RC4/ModelLink/pretrain_gpt.py", line 222, in main
    initialize_megatron(extra_args_provider=extra_args_provider,
  File "/workspace/RC4/ModelLink/modellink/training/initialize.py", line 72, in initialize_megatron
    pretrain(train_valid_test_datasets_provider,
  File "/workspace/RC4/ModelLink/modellink/training/training.py", line 291, in pretrain
    args = parse_args(extra_args_provider, ignore_unknown_args)
  File "/workspace/RC4/ModelLink/modellink/training/arguments.py", line 37, in wrapper
    return parse_args(decorated_provider, ignore_unknown_args)
  File "/workspace/RC4/ModelLink/modellink/training/arguments.py", line 37, in wrapper
    initialize_megatron(extra_args_provider=extra_args_provider,
    return parse_args(decorated_provider, ignore_unknown_args)  File "/workspace/RC4/ModelLink/modellink/training/initialize.py", line 72, in initialize_megatron

  File "/workspace/RC4/ModelLink/megatron/training/arguments.py", line 86, in parse_args
        args = parse_args(extra_args_provider, ignore_unknown_args)args = load_json_args(args.flexpipe_config, args)

  File "/workspace/RC4/ModelLink/modellink/training/arguments.py", line 37, in wrapper
  File "/workspace/RC4/ModelLink/megatron/training/json_arguments.py", line 13, in load_json_args
    args.flex_recompute_activations = config_dict["flex_recompute_activations"]
    KeyErrorreturn parse_args(decorated_provider, ignore_unknown_args): 
'flex_recompute_activations'
  File "/workspace/RC4/ModelLink/modellink/training/arguments.py", line 37, in wrapper
    return parse_args(decorated_provider, ignore_unknown_args)
  File "/workspace/RC4/ModelLink/megatron/training/arguments.py", line 86, in parse_args
    args = load_json_args(args.flexpipe_config, args)
  File "/workspace/RC4/ModelLink/megatron/training/json_arguments.py", line 13, in load_json_args
    args.flex_recompute_activations = config_dict["flex_recompute_activations"]
KeyError: 'flex_recompute_activations'
[ERROR] 2024-12-06-18:06:14 (PID:225411, Device:-1, RankID:-1) ERR99999 UNKNOWN application exception
[ERROR] 2024-12-06-18:06:14 (PID:225413, Device:-1, RankID:-1) ERR99999 UNKNOWN application exception
/home/ma-user/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/tempfile.py:821: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmpcoibh5yx'>
  _warnings.warn(warn_message, ResourceWarning)
/home/ma-user/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/tempfile.py:821: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmpdw4azux8'>
  _warnings.warn(warn_message, ResourceWarning)
##############################
!!!!!!!!!!!!!!!!!!!
##############################
!!!!!!!!!!!!!!!!!!!
Traceback (most recent call last):
  File "/workspace/RC4/ModelLink/pretrain_gpt.py", line 229, in <module>
    main()
  File "/workspace/RC4/ModelLink/pretrain_gpt.py", line 222, in main
    pretrain(train_valid_test_datasets_provider,
  File "/workspace/RC4/ModelLink/modellink/training/training.py", line 291, in pretrain
    initialize_megatron(extra_args_provider=extra_args_provider,
  File "/workspace/RC4/ModelLink/modellink/training/initialize.py", line 72, in initialize_megatron
    args = parse_args(extra_args_provider, ignore_unknown_args)
  File "/workspace/RC4/ModelLink/modellink/training/arguments.py", line 37, in wrapper
    return parse_args(decorated_provider, ignore_unknown_args)
  File "/workspace/RC4/ModelLink/modellink/training/arguments.py", line 37, in wrapper
    return parse_args(decorated_provider, ignore_unknown_args)
  File "/workspace/RC4/ModelLink/megatron/training/arguments.py", line 86, in parse_args
    args = load_json_args(args.flexpipe_config, args)
  File "/workspace/RC4/ModelLink/megatron/training/json_arguments.py", line 13, in load_json_args
    args.flex_recompute_activations = config_dict["flex_recompute_activations"]
KeyError: 'flex_recompute_activations'
Traceback (most recent call last):
  File "/workspace/RC4/ModelLink/pretrain_gpt.py", line 229, in <module>
    main()
  File "/workspace/RC4/ModelLink/pretrain_gpt.py", line 222, in main
[ERROR] 2024-12-06-18:06:14 (PID:225412, Device:-1, RankID:-1) ERR99999 UNKNOWN application exception
    pretrain(train_valid_test_datasets_provider,
  File "/workspace/RC4/ModelLink/modellink/training/training.py", line 291, in pretrain
    initialize_megatron(extra_args_provider=extra_args_provider,
  File "/workspace/RC4/ModelLink/modellink/training/initialize.py", line 72, in initialize_megatron
    args = parse_args(extra_args_provider, ignore_unknown_args)
  File "/workspace/RC4/ModelLink/modellink/training/arguments.py", line 37, in wrapper
    return parse_args(decorated_provider, ignore_unknown_args)
  File "/workspace/RC4/ModelLink/modellink/training/arguments.py", line 37, in wrapper
    return parse_args(decorated_provider, ignore_unknown_args)
  File "/workspace/RC4/ModelLink/megatron/training/arguments.py", line 86, in parse_args
    args = load_json_args(args.flexpipe_config, args)
  File "/workspace/RC4/ModelLink/megatron/training/json_arguments.py", line 13, in load_json_args
    args.flex_recompute_activations = config_dict["flex_recompute_activations"]
KeyError: 'flex_recompute_activations'
/home/ma-user/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/tempfile.py:821: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmp83et7zkz'>
  _warnings.warn(warn_message, ResourceWarning)
[ERROR] 2024-12-06-18:06:14 (PID:225414, Device:-1, RankID:-1) ERR99999 UNKNOWN application exception
/home/ma-user/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/tempfile.py:821: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmpdk8qqeqi'>
  _warnings.warn(warn_message, ResourceWarning)
##############################
!!!!!!!!!!!!!!!!!!!
##############################
!!!!!!!!!!!!!!!!!!!
Traceback (most recent call last):
  File "/workspace/RC4/ModelLink/pretrain_gpt.py", line 229, in <module>
    main()
  File "/workspace/RC4/ModelLink/pretrain_gpt.py", line 222, in main
    pretrain(train_valid_test_datasets_provider,
  File "/workspace/RC4/ModelLink/modellink/training/training.py", line 291, in pretrain
    initialize_megatron(extra_args_provider=extra_args_provider,
  File "/workspace/RC4/ModelLink/modellink/training/initialize.py", line 72, in initialize_megatron
    args = parse_args(extra_args_provider, ignore_unknown_args)
  File "/workspace/RC4/ModelLink/modellink/training/arguments.py", line 37, in wrapper
    return parse_args(decorated_provider, ignore_unknown_args)
  File "/workspace/RC4/ModelLink/modellink/training/arguments.py", line 37, in wrapper
    return parse_args(decorated_provider, ignore_unknown_args)
  File "/workspace/RC4/ModelLink/megatron/training/arguments.py", line 86, in parse_args
    args = load_json_args(args.flexpipe_config, args)
  File "/workspace/RC4/ModelLink/megatron/training/json_arguments.py", line 13, in load_json_args
    args.flex_recompute_activations = config_dict["flex_recompute_activations"]
KeyError: 'flex_recompute_activations'
Traceback (most recent call last):
  File "/workspace/RC4/ModelLink/pretrain_gpt.py", line 229, in <module>
    main()
  File "/workspace/RC4/ModelLink/pretrain_gpt.py", line 222, in main
    pretrain(train_valid_test_datasets_provider,
  File "/workspace/RC4/ModelLink/modellink/training/training.py", line 291, in pretrain
    initialize_megatron(extra_args_provider=extra_args_provider,
  File "/workspace/RC4/ModelLink/modellink/training/initialize.py", line 72, in initialize_megatron
    args = parse_args(extra_args_provider, ignore_unknown_args)
  File "/workspace/RC4/ModelLink/modellink/training/arguments.py", line 37, in wrapper
    return parse_args(decorated_provider, ignore_unknown_args)
  File "/workspace/RC4/ModelLink/modellink/training/arguments.py", line 37, in wrapper
    return parse_args(decorated_provider, ignore_unknown_args)
  File "/workspace/RC4/ModelLink/megatron/training/arguments.py", line 86, in parse_args
    args = load_json_args(args.flexpipe_config, args)
  File "/workspace/RC4/ModelLink/megatron/training/json_arguments.py", line 13, in load_json_args
    args.flex_recompute_activations = config_dict["flex_recompute_activations"]
KeyError: 'flex_recompute_activations'
[ERROR] 2024-12-06-18:06:14 (PID:225409, Device:-1, RankID:-1) ERR99999 UNKNOWN application exception
[ERROR] 2024-12-06-18:06:14 (PID:225410, Device:-1, RankID:-1) ERR99999 UNKNOWN application exception
/home/ma-user/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/tempfile.py:821: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmpcbb3_g_s'>
  _warnings.warn(warn_message, ResourceWarning)
/home/ma-user/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/tempfile.py:821: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmpkouk_0zr'>
  _warnings.warn(warn_message, ResourceWarning)
[2024-12-06 18:06:15,309] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 225409 closing signal SIGTERM
[2024-12-06 18:06:15,310] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 225410 closing signal SIGTERM
[2024-12-06 18:06:15,310] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 225411 closing signal SIGTERM
[2024-12-06 18:06:15,310] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 225412 closing signal SIGTERM
[2024-12-06 18:06:15,310] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 225413 closing signal SIGTERM
[2024-12-06 18:06:15,310] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 225414 closing signal SIGTERM
[2024-12-06 18:06:15,310] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 225415 closing signal SIGTERM
