[2024-12-12 18:50:46,648] torch.distributed.run: [WARNING] 
[2024-12-12 18:50:46,648] torch.distributed.run: [WARNING] *****************************************
[2024-12-12 18:50:46,648] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
[2024-12-12 18:50:46,648] torch.distributed.run: [WARNING] *****************************************
/home/ma-user/anaconda3/envs/PyTorch-2.1.0/bin/python3.9: can't open file '/workspace/RC4/Ascend-aceso/aceso/aceso_execute/pretrain_gpt.py': [Errno 2] No such file or directory
/home/ma-user/anaconda3/envs/PyTorch-2.1.0/bin/python3.9: can't open file '/workspace/RC4/Ascend-aceso/aceso/aceso_execute/pretrain_gpt.py': [Errno 2] No such file or directory
/home/ma-user/anaconda3/envs/PyTorch-2.1.0/bin/python3.9: can't open file '/workspace/RC4/Ascend-aceso/aceso/aceso_execute/pretrain_gpt.py': [Errno 2] No such file or directory
/home/ma-user/anaconda3/envs/PyTorch-2.1.0/bin/python3.9: can't open file '/workspace/RC4/Ascend-aceso/aceso/aceso_execute/pretrain_gpt.py': [Errno 2] No such file or directory
/home/ma-user/anaconda3/envs/PyTorch-2.1.0/bin/python3.9: can't open file '/workspace/RC4/Ascend-aceso/aceso/aceso_execute/pretrain_gpt.py': [Errno 2] No such file or directory
/home/ma-user/anaconda3/envs/PyTorch-2.1.0/bin/python3.9: can't open file '/workspace/RC4/Ascend-aceso/aceso/aceso_execute/pretrain_gpt.py': [Errno 2] No such file or directory
/home/ma-user/anaconda3/envs/PyTorch-2.1.0/bin/python3.9: can't open file '/workspace/RC4/Ascend-aceso/aceso/aceso_execute/pretrain_gpt.py': [Errno 2] No such file or directory
/home/ma-user/anaconda3/envs/PyTorch-2.1.0/bin/python3.9: can't open file '/workspace/RC4/Ascend-aceso/aceso/aceso_execute/pretrain_gpt.py': [Errno 2] No such file or directory
[2024-12-12 18:50:51,736] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 2) local_rank: 0 (pid: 28675) of binary: /home/ma-user/anaconda3/envs/PyTorch-2.1.0/bin/python3.9
